#!/usr/bin/env bash

# Deletes YAML frontmatter tags in markdowns for neuron entries
#
# Author:   Mark Lucernas
# Date:     Aug 21, 2021
# License:  MIT

set -o pipefail
set -o nounset

SCRIPT_PATH="$(realpath -- "${0}")"
while [ -h "${SCRIPT_PATH}" ]; do
  SCRIPT_DIR="$(cd -P "$(dirname "${SCRIPT_PATH}")" >/dev/null 2>&1 && pwd)"
  SCRIPT_PATH="$(readlink "${SCRIPT_PATH}")"
  [[ "${SCRIPT_PATH}" != /* ]] && SCRIPT_PATH="${SCRIPT_DIR}/${SCRIPT_PATH}"
done
SCRIPT_DIR="$(cd -P "$(dirname "${SCRIPT_PATH}")" >/dev/null 2>&1 && pwd)"
SCRIPT_NAME="$(basename -- "${SCRIPT_PATH}")"

usage() {
cat << EOF
USAGE: <required> [optional]

  ./${SCRIPT_NAME} [!] <content-pattern> <tag> [all] [directory]
  ./${SCRIPT_NAME} "lorem ipsum" 'new-tag' .
  ./${SCRIPT_NAME} ! "lorem ipsum" 'new-*' test-dir/
  ./${SCRIPT_NAME} "lorem ipsum" 'new-*' 1
  ./${SCRIPT_NAME} ! "lorem ipsum" 'new-*' 1 test-dir/

  [!]                 Only include files not matching <content-pattern>.
  <content-pattern>   regex pattern to match the file(s) content to be included
                      in tag deletion.
  <tag>               name of tag to delete.
  [all]               0 (default) to delete first match. 1 to delete all
                      matching pattern.
  [directory]         directory (default '.') to search into, recursively.

EOF
}

if [[ ${#} -gt 5 ]] || [[ ${#} -lt 2 ]]; then
  usage
  echo "ERROR: arg count: ${#}"
  exit 1
fi

if [[ -n ${1+x} ]]; then
  if [[ "${1}" == "!" ]]; then
    GREP_FLAGS=-rLi
    shift 1
  else
    GREP_FLAGS=-rli
  fi
else
  usage
  exit 1
fi

if [[ -n ${1+x} ]]; then
  PATTERN="${1}"
else
  usage
  exit 1
fi

if [[ -n ${2+x} ]]; then
  TAG="${2}"
else
  usage
  exit 1
fi

if [[ -n ${3+x} ]] && [[ "${3:-.}" != "." ]] && [[ "${3}" -eq "${3}" ]]; then
  ALL=${3}
  shift 1
else
  ALL=0
fi

TARGET_DIR="${3:-.}"
if ! [[ -d "${TARGET_DIR}" ]]; then
  usage
  echo "ERROR: Target directory does not exist"
  exit 1
else
  # Strip trailing whitespace
  TARGET_DIR=$(echo "${TARGET_DIR}" | sed 's,/*$,,')
fi

readonly GREP_FLAGS
readonly PATTERN
readonly TAG
readonly ALL
readonly TARGET_DIR

readonly SCRIPT_PATH
readonly SCRIPT_DIR
readonly SCRIPT_NAME
readonly INDENT="  "

MATCH_FILES="$( \
  grep ${GREP_FLAGS} \
  --exclude-dir=".git" \
  --exclude-dir=".neuron" \
  --exclude-dir=".github" \
  --exclude-dir=".static" \
  --exclude-dir=".vscode" \
  --exclude="index.md" \
  --exclude="todo.md" \
  --exclude="faq.md" \
  --exclude="README.md" \
  --exclude="LICENSE.md" \
  -- \
  "${PATTERN}" \
  ${TARGET_DIR}/*.md \
)"

for file in $MATCH_FILES; do
  line_nr="$(awk "/tags:/{ print NR; exit }" "${file}")"

  begin_meta=0
  begin_tags=0
  while IFS='' read -r line || [ -n "${line}" ]; do

    # Bound search only within metadata space
    if [[ "${line}" == "---" ]]; then
      if [[ ${begin_meta} -eq 0 ]]; then
        begin_meta=1
        continue
      else
        break
      fi
    fi

    # Bound search only under tags meta
    if [[ "${line}" =~ tags:* ]] && [[ ${begin_tags} -eq 0 ]]; then
      begin_tags=1
      continue
    elif [[ ${begin_tags} -eq 1 ]]; then

      if [[ "${line}" =~ ${INDENT}-\ ${TAG} ]]; then
        ((line_nr++))
        echo "Deleting '${TAG}' tag from ${file}:${line_nr}..."
        sed -i "${line_nr}d" "${file}"
        if [[ ${ALL} -eq 0 ]]; then
          break
        else
          ((line_nr--))
        fi
      elif [[ "${line}" =~ ${INDENT}-* ]]; then
        ((line_nr++))
        continue
      else
        break
      fi
    else
      continue
    fi
  done < ${file}

  # Delete tags: meta if no more tags
  if [[ ${begin_tags} -eq 1 ]]; then
    line_nr="$(awk "/tags:/{ print NR; exit }" "${file}")"
    next=$(sed -n "$((line_nr+1))p" "${file}")
    if [[ -n ${line_nr} ]] && ! [[ "${next}" =~ ${INDENT}-.* ]]; then
      sed -i "${line_nr}d" "${file}"
    fi
  fi

  # Delete both --- metadata fence if no more metas
  if [[ ${begin_meta} -eq 1 ]]; then
    line_nr="$(awk "/---/{ print NR; exit }" "${file}")"
    next=$(sed -n "$((line_nr+1))p" "${file}")
    if [[ -n ${line_nr} ]] && [[ "${next}" == '---' ]]; then
      sed -i "${line_nr}d" "${file}"
      sed -i "${line_nr}d" "${file}"
    fi
  fi
done

if [[ -z ${MATCH_FILES} ]]; then
  echo "no matching file"
else
  echo "Done!"
fi
